services:
  api:
    build:
      context: .
    volumes:
      - ./:/usr/src/app
    env_file:
      - ./.env
    environment:
      - DB_URL=postgres://postgres:root@database:5432/postgres
      - DB_HOST=database
    container_name: payments-api
    ports:
      - 3000:3000
    command: npm run dev
  database:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: "root"
    container_name: payments-db
    ports:
      - "5432:5432"
