services:
  api:
    build:
      context: .
    volumes:
      - ./:/usr/src/app
    env_file:
      - ./.env
    container_name: payments-api
    ports:
      - 3000:3000
    command: npm run dev
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: "root"
    container_name: payments-db
    ports:
      - "5432:5432"

